# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'electrum_nmc/electrum/gui/qt/forms/tradenamedialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TradeNameDialog(object):
    def setupUi(self, TradeNameDialog):
        TradeNameDialog.setObjectName("TradeNameDialog")
        TradeNameDialog.resize(545, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TradeNameDialog.sizePolicy().hasHeightForWidth())
        TradeNameDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(TradeNameDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.labelNamespace = QtWidgets.QLabel(TradeNameDialog)
        self.labelNamespace.setText("Domain")
        self.labelNamespace.setObjectName("labelNamespace")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelNamespace)
        self.labelName = QtWidgets.QLabel(TradeNameDialog)
        self.labelName.setText("example.bit")
        self.labelName.setTextFormat(QtCore.Qt.PlainText)
        self.labelName.setObjectName("labelName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelName)
        spacerItem = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.amountLabel = QtWidgets.QLabel(TradeNameDialog)
        self.amountLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.amountLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.dataLabel = QtWidgets.QLabel(TradeNameDialog)
        self.dataLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dataLabel.setObjectName("dataLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.dataLabel)
        self.dataEditHorizontalLayout = QtWidgets.QHBoxLayout()
        self.dataEditHorizontalLayout.setObjectName("dataEditHorizontalLayout")
        self.dataEdit = QtWidgets.QLineEdit(TradeNameDialog)
        self.dataEdit.setMaxLength(520)
        self.dataEdit.setObjectName("dataEdit")
        self.dataEditHorizontalLayout.addWidget(self.dataEdit)
        self.btnDNSEditor = QtWidgets.QPushButton(TradeNameDialog)
        self.btnDNSEditor.setObjectName("btnDNSEditor")
        self.dataEditHorizontalLayout.addWidget(self.btnDNSEditor)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.dataEditHorizontalLayout)
        self.dataHintLabel = QtWidgets.QLabel(TradeNameDialog)
        self.dataHintLabel.setOpenExternalLinks(True)
        self.dataHintLabel.setObjectName("dataHintLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dataHintLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.labelTransferTo = QtWidgets.QLabel(TradeNameDialog)
        self.labelTransferTo.setObjectName("labelTransferTo")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.labelTransferTo)
        self.transferToLayout = QtWidgets.QHBoxLayout()
        self.transferToLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.transferToLayout.setSpacing(0)
        self.transferToLayout.setObjectName("transferToLayout")
        self.transferTo = QPayToEdit(TradeNameDialog)
        self.transferTo.setObjectName("transferTo")
        self.transferToLayout.addWidget(self.transferTo)
        self.formLayout.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.transferToLayout)
        self.labelTransferToHint = QtWidgets.QLabel(TradeNameDialog)
        self.labelTransferToHint.setObjectName("labelTransferToHint")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.labelTransferToHint)
        spacerItem3 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(11, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.labelOffer = QtWidgets.QLabel(TradeNameDialog)
        self.labelOffer.setObjectName("labelOffer")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.labelOffer)
        self.offerLayout = QtWidgets.QHBoxLayout()
        self.offerLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.offerLayout.setSpacing(0)
        self.offerLayout.setObjectName("offerLayout")
        self.inputOffer = QtWidgets.QPlainTextEdit(TradeNameDialog)
        self.inputOffer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.inputOffer.setObjectName("inputOffer")
        self.offerLayout.addWidget(self.inputOffer)
        self.formLayout.setLayout(12, QtWidgets.QFormLayout.FieldRole, self.offerLayout)
        self.horizontalLayout_amountEdit = QtWidgets.QHBoxLayout()
        self.horizontalLayout_amountEdit.setObjectName("horizontalLayout_amountEdit")
        self.amountEdit = QtWidgets.QLineEdit(TradeNameDialog)
        self.amountEdit.setObjectName("amountEdit")
        self.horizontalLayout_amountEdit.addWidget(self.amountEdit)
        self.fiatAmountEdit = QtWidgets.QLineEdit(TradeNameDialog)
        self.fiatAmountEdit.setObjectName("fiatAmountEdit")
        self.horizontalLayout_amountEdit.addWidget(self.fiatAmountEdit)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_amountEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.labelSubmitSellHint = QtWidgets.QLabel(TradeNameDialog)
        self.labelSubmitSellHint.setText("If you leave the Buy Offer field blank, you are committing to sell this name to anyone who pays the specified price.<br><br>If you want control over whom you sell this name to (or if you already possess a Buy Offer), paste a specific Buy Offer to accept (the trade will take approximately 10 minutes to 2 hours).")
        self.labelSubmitSellHint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSubmitSellHint.setIndent(10)
        self.labelSubmitSellHint.setWordWrap(True)
        self.labelSubmitSellHint.setObjectName("labelSubmitSellHint")
        self.verticalLayout.addWidget(self.labelSubmitSellHint)
        self.labelSubmitBuyHint = QtWidgets.QLabel(TradeNameDialog)
        self.labelSubmitBuyHint.setText("If you leave the Sell Offer field blank, you are committing to buy this name from anyone who owns it and accepts the specified price.<br><br>If you already possess a Sell Offer, paste it to accept (the trade will take approximately 10 minutes to 2 hours).")
        self.labelSubmitBuyHint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSubmitBuyHint.setIndent(10)
        self.labelSubmitBuyHint.setWordWrap(True)
        self.labelSubmitBuyHint.setObjectName("labelSubmitBuyHint")
        self.verticalLayout.addWidget(self.labelSubmitBuyHint)
        self.outputOffer = QtWidgets.QPlainTextEdit(TradeNameDialog)
        self.outputOffer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.outputOffer.setReadOnly(True)
        self.outputOffer.setObjectName("outputOffer")
        self.verticalLayout.addWidget(self.outputOffer)
        self.labelOutputSellHint = QtWidgets.QLabel(TradeNameDialog)
        self.labelOutputSellHint.setText("Publish the above Sell Offer wherever a potential buyer might see it.  Once you\'ve published it, click OK to freeze this name so that the Sell Offer stays valid.  You can change your mind and revoke your Sell Offer by unfreezing this name and then updating or renewing it.  If you want to update or renew this name while waiting for a buyer, you will need to unfreeze it first and then re-create and re-publish the Sell Offer after issuing the update.")
        self.labelOutputSellHint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelOutputSellHint.setIndent(10)
        self.labelOutputSellHint.setWordWrap(True)
        self.labelOutputSellHint.setObjectName("labelOutputSellHint")
        self.verticalLayout.addWidget(self.labelOutputSellHint)
        self.labelOutputBuyHint = QtWidgets.QLabel(TradeNameDialog)
        self.labelOutputBuyHint.setText("Publish the above Buy Offer wherever the current name owner might see it.  Once you\'ve published it, click OK to freeze the coins that you used for this Buy Offer so that the Buy Offer stays valid.  You can change your mind and revoke your Buy Offer by unfreezing the coins used in this Buy Offer and then spending them.")
        self.labelOutputBuyHint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelOutputBuyHint.setIndent(10)
        self.labelOutputBuyHint.setWordWrap(True)
        self.labelOutputBuyHint.setObjectName("labelOutputBuyHint")
        self.verticalLayout.addWidget(self.labelOutputBuyHint)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.buttonBox = QtWidgets.QDialogButtonBox(TradeNameDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.amountLabel.setBuddy(self.amountEdit)
        self.dataLabel.setBuddy(self.dataEdit)
        self.labelTransferTo.setBuddy(self.transferTo)
        self.labelOffer.setBuddy(self.inputOffer)

        self.retranslateUi(TradeNameDialog)
        self.buttonBox.rejected.connect(TradeNameDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TradeNameDialog)

    def retranslateUi(self, TradeNameDialog):
        _translate = QtCore.QCoreApplication.translate
        TradeNameDialog.setWindowTitle(_translate("TradeNameDialog", "Trade Name"))
        self.amountLabel.setText(_translate("TradeNameDialog", "Requested &amount:"))
        self.dataLabel.setText(_translate("TradeNameDialog", "&Data:"))
        self.dataEdit.setToolTip(_translate("TradeNameDialog", "Enter JSON string that will be associated with the name"))
        self.btnDNSEditor.setText(_translate("TradeNameDialog", "DNS Editor…"))
        self.dataHintLabel.setText(_translate("TradeNameDialog", "JSON string, e.g. {&quot;ip&quot;: [&quot;1.2.3.4&quot;, &quot;1.2.3.5&quot;]}<br>See <a href=\"https://github.com/namecoin/proposals\">JSON value specifications</a>."))
        self.labelTransferTo.setText(_translate("TradeNameDialog", "&Transfer to:"))
        self.labelTransferToHint.setText(_translate("TradeNameDialog", "(Leave empty if not transferring.)"))
        self.labelOffer.setText(_translate("TradeNameDialog", "&Buy Offer to accept:"))
        self.amountEdit.setToolTip(_translate("TradeNameDialog", "Amount in NMC"))
        self.fiatAmountEdit.setToolTip(_translate("TradeNameDialog", "Amount in fiat"))
        self.outputOffer.setPlainText(_translate("TradeNameDialog", "0123456789abcdef"))
from .qpaytoedit import QPayToEdit


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TradeNameDialog = QtWidgets.QDialog()
    ui = Ui_TradeNameDialog()
    ui.setupUi(TradeNameDialog)
    TradeNameDialog.show()
    sys.exit(app.exec_())
